# Minecraft / Fabric versions
minecraft_version=26.2
loader_version=0.19.3
loom_version=1.17.20

# Mod
mod_version=2.3.0
maven_group=com.thatapplefreak.voxelcam
archives_base_name=voxelcam

# Dependencies
fabric_version=0.158.0+26.2
junit_version=6.1.3
client_gametest_version=6.0.0+515ac5339e

org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
