# Minecraft / Fabric versions
minecraft_version=1.21.11
yarn_mappings=1.21.11+build.6
loader_version=0.19.3

# Mod
mod_version=2.0.0
maven_group=com.thatapplefreak.voxelcam
archives_base_name=voxelcam

# Dependencies
fabric_version=0.141.6+1.21.11

org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
